# skim_version = "v1_0" 
# skim_version = "v1_1" # Redo Bs skim with fixed MC sample
# skim_version = "v1_2" # Fix gen particles, 531 was not in the list
#skim_version = "v1_3" # Add all leptons and their parents+grandparents to the saved gen particles
#skim_version = "v1_4" # Lower pT cut on Bs Ks to 0.5, symmetrize phi window to [0.96, 1.08]. Also, Bs to KKuu probefilter has more stats.
#skim_version = "v1_5" # Loosed pre-vtx phi window to [0.52, 1.52]. Set post-vtx phi window to [0.96, 1.08].
#skim_version = "v1_5_veryloose" # Remove almost all vtx reqs to debug efficiency loss
#skim_version = "v1_6" # More pre-vtx loosening, e.g. trk eta < 2.5, not 2.4
#skim_version = "v1_6_lzma6" # Test compression level 6
#skim_version = "v1_6_zlib6" # Test ZLIB compression level 6
#skim_version = "v1_7" # v1_6 data had 200 LS/job, which caused timeouts. Try 50 instead (might have to hadd)
#skim_version = "v1_7_1" # Redo 1_7 failed jobs, which expired
#skim_version = "v1_7_2" # Bug-fix and ext Bs_probefilter MC

#skim_version = "v2_0" # Add Jpsi mass constraint.
#skim_version = "v2_1" # Fix ordering of tracks passed to KinVtxFitter.
#skim_version = "v2_2" # Fix output data - leptons and tracks were mixed up.
#skim_version = "v2_2_1" # CRAB wasn't working. Try again.
#skim_version = "v2_3" # Fix memory leak (hopefully)
#skim_version = "v2_3_1" # Resubmit 2018D2_part3 and 2018D2_part5
#skim_version = "vTEST" # Helping out Stefano
#skim_version = "v2_4" # Lower track pT cut from 700 to 500 MeV.
#skim_version = "v2_5" # Lower phi and Kstar pT cut from 2 GeV to 750 MeV, and add specific trigger matching info
#skim_version = "v2_5_1" # Bug fix: no muons were passing...
#skim_version = "v2_5_2" # Bug fix: didn't upload pT cut changes :(
#skim_version = "v2_5_3" # Try even lower track pT, 300 MeV
#skim_version = "v2_5_4" # Back to trk pT 500 MeV, phi pT 750 MeV, remove dimuon dR>0.03
#skim_version = "vTEST" # Testing data production
#skim_version = "v2_6" # Bump version for data production
skim_version = "v2_6_1" # Retry 2018D with auto splitting