import FWCore.ParameterSet.Config as cms
from PhysicsTools.NanoAOD.common_cff import *



trgTable = cms.EDProducer( "TrgBitTableProducer",
                          hltresults = cms.InputTag("TriggerResults::HLT"),
                          l1results  = cms.InputTag("gtStage2Digis::RECO"),
                          #add interesting paths
                          paths      = cms.vstring(
                                             "HLT_Mu7_IP4",
                                             "HLT_Mu8_IP6",
                                             "HLT_Mu8_IP5",
                                             "HLT_Mu8_IP3",
                                             "HLT_Mu8p5_IP3p5",
                                             "HLT_Mu9_IP6",
                                             "HLT_Mu9_IP5",
                                             "HLT_Mu9_IP4",    
                                             "HLT_Mu10p5_IP3p5",
                                             "HLT_Mu12_IP6", 
                                             "HLT_DoubleMu40NoFiltersNoVtxDisplaced", 
                                             "HLT_DoubleMu43NoFiltersNoVtx", 
                                             "HLT_DoubleMu48NoFiltersNoVtx", 
                                             "HLT_DoubleMu4_3_Bs", 
                                             "HLT_DoubleMu4_3_Jpsi", 
                                             "HLT_DoubleMu4_JpsiTrkTrk_Displaced", 
                                             "HLT_DoubleMu4_JpsiTrk_Displaced", 
                                             "HLT_DoubleMu4_Jpsi_Displaced", 
                                             "HLT_DoubleMu4_Jpsi_NoVertexing", 
                                             "HLT_DoubleMu4_LowMassNonResonantTrk_Displaced", 
                                             "HLT_DoubleMu4_Mass3p8_DZ_PFHT350", 
                                             "HLT_DoubleMu4_Mass8_DZ_PFHT350", 
                                             "HLT_DoubleMu4_PsiPrimeTrk_Displaced", 
                                             "HLT_Dimuon0_Jpsi", 
                                             "HLT_Dimuon0_Jpsi3p5_Muon2", 
                                             "HLT_Dimuon0_Jpsi_L1_4R_0er1p5R", 
                                             "HLT_Dimuon0_Jpsi_L1_NoOS", 
                                             "HLT_Dimuon0_Jpsi_NoVertexing", 
                                             "HLT_Dimuon0_Jpsi_NoVertexing_L1_4R_0er1p5R", 
                                             "HLT_Dimuon0_Jpsi_NoVertexing_NoOS", 
                                             "HLT_Dimuon20_Jpsi_Barrel_Seagulls", 
                                             "HLT_Dimuon25_Jpsi", 
                                             "HLT_Dimuon25_Jpsi_noCorrL1", 
                                             "HLT_DoubleMu2_Jpsi_DoubleTkMu0_Phi", 
                                             "HLT_DoubleMu2_Jpsi_DoubleTrk1_Phi1p05", 
                                             "HLT_HIL3DoubleMuOpen_JpsiPsi", 
                                             "HLT_Mu7p5_L2Mu2_Jpsi", 
                                             "HLT_Mu7p5_Track2_Jpsi", 
                                             "HLT_Mu7p5_Track3p5_Jpsi", 
                                             "HLT_Mu7p5_Track7_Jpsi", 
                                            ),
                           #add interesting seeds
                           seeds     = cms.vstring(
                                             "L1_SingleMu7er1p5",
                                             "L1_SingleMu8er1p5",
                                             "L1_SingleMu9er1p5",
                                             "L1_SingleMu10er1p5",
                                             "L1_SingleMu12er1p5",
                                             "L1_SingleMu22", 
                                             "L1_DoubleMu0", 
                                             "L1_DoubleMu_12_5", 
                                             "L1_DoubleMu_15_7", 
                                             "L1_DoubleMu18er2p1", 
                                             "L1_DoubleMu0er2p0_SQ_dR_Max1p4", 
                                             "L1_DoubleMu0er1p5_SQ_dR_Max1p4", 
                                             "L1_DoubleMu3_SQ_ETMHF50_Jet60er2p5", 
                                             "L1_DoubleMu3_SQ_ETMHF50_Jet60er2p5_OR_DoubleJet40er2p5", 
                                             "L1_DoubleMu3_SQ_HTT220er", 
                                             "L1_DoubleMu3_SQ_HTT240er", 
                                             "L1_DoubleMu_15_5_SQ", 
                                             "L1_DoubleMu_15_7_SQ", 
                                             "L1_DoubleMu_15_7_Mass_Min1", 
                                             "L1_DoubleMu0_Mass_Min1", 
                                             "L1_DoubleMu0_OQ", 
                                             "L1_DoubleMu5_SQ_EG9er2p5", 
                                             "L1_DoubleMu0er1p5_SQ_OS_dR_Max1p4", 
                                             "L1_DoubleMu4p5er2p0_SQ_OS_Mass_Min7", 
                                             "L1_DoubleMu4_SQ_OS_dR_Max1p2", 
                                             "L1_DoubleMu0er1p4_SQ_OS_dR_Max1p4", 
                                             "L1_DoubleMu4p5_SQ_OS_dR_Max1p2", 
                                             "L1_DoubleMu9_SQ", 
                                             "L1_DoubleMu0_SQ", 
                                             "L1_DoubleMu0_SQ_OS", 
                                             "L1_DoubleMu4p5_SQ_OS", 
                                             "L1_DoubleMu4p5er2p0_SQ_OS", 
                                             "L1_DoubleMu0er1p5_SQ_OS", 
                                             "L1_DoubleMu4_SQ_OS", 
                                             "L1_DoubleMu5Upsilon_OS_DoubleEG3", 
                                             "L1_DoubleMu3_OS_DoubleEG7p5Upsilon", 
                                             "L1_DoubleMu3_SQ_ETMHF60_Jet60er2p5", 
                                             "L1_DoubleMu3_SQ_ETMHF50_HTT60er", 
                                             "L1_DoubleMu8_SQ", 
                                             "L1_DoubleMu3_SQ_HTT260er", 
                                             "L1_DoubleMu4_SQ_EG9er2p5", 
                                             "L1_DoubleMu0er2p0_SQ_OS_dR_Max1p4", 
                                             "L1_DoubleMu0er1p5_SQ", 
                                             "L1_DoubleMu3_dR_Max1p6_Jet90er2p5_dR_Max0p8", 
                                             "L1_DoubleMu0_dR_Max1p6_Jet90er2p5_dR_Max0p8", 
                                             "L1_DoubleMu4p5er2p0_SQ_OS_Mass7to18",                                              
                                              ),
                            
)

trgTables = cms.Sequence(trgTable)



